---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

# ENABLE:  # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS:  # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  # - COPYPASTE  # Uncomment to disable checks of excessive copy-pastes
  - SPELL  # disable checks of spelling mistakes

DISABLE_LINTERS:
  - PYTHON_PYRIGHT
  - JSON_PRETTIER
  - YAML_PRETTIER
  - HTML_HTMLHINT

DISABLE_ERRORS_LINTERS:
  - PYTHON_PYLINT

PYTHON_PYLINT_CONFIG_FILE: "pyproject.toml"
PYTHON_PYLINT_PRE_COMMANDS:
  - command: pip install django==6.0.5 pylint-django==2.7.0
    run_before_linters: true

PRINT_ALL_FILES: false
VALIDATE_ALL_CODEBASE: true

EXCLUDED_DIRECTORIES: []

PYTHON_DEFAULT_STYLE: black  # or ruff

REPOSITORY_TRIVY_ARGUMENTS:
  - --skip-dirs
  - tests
  - --skip-dirs
  - .venv

REPORTERS_MARKDOWN_SUMMARY_TYPE: sections
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: false

# PLUGINS:
#  - https://raw.githubusercontent.com/oxsecurity/megalinter/main/.automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml
ACTION_ZIZMOR_UNSECURED_ENV_VARIABLES:
  - GITHUB_TOKEN
