[project]
name = "dts-sed-app"
version = "0.1.0"  # x-release-please-version
requires-python = ">= 3.10"
dependencies = [
    "Django==5.2.14",  # latest version supported by python 3.10
#    "Django==6.0.5",
    "django-allauth==65.16.1",
    "django-allauth-ui==1.8.1",
    "django-widget-tweaks==1.5.1",
    "slippers==0.6.3",  # allauth-ui v1.8.1 cannot use v7
    "typeguard==2.13.3",  # slippers does not support newer versions
    "whitenoise==6.12.0",
    "python-dotenv==1.2.2",
]
optional-dependencies.dev = [
    "black>=26.3.1",
    "ruff>=0.15",
    "bandit>=1.9.4",
    "isort>=8.0.1",
    "yamllint>=1.38",
    "yamlfix>=1.19",
    "pylint>=4.0.5",
]
optional-dependencies.test = [
    "pytest>=9.0",
    "pytest-cov>=7.1",
    "pytest-django>=4.12",
]

[tool.setuptools.packages.find]
include = ["learning"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "learning.settings"
python_files = [
    "test_*.py",
    "*_tests.py",
    "tests.py",
]
django_debug_mode = false
addopts = "--reuse-db --durations=10"  # use reusable database for faster local test runs and show slow tests

[tool.coverage.run]
branch = true
source = [
    "learning",
]
omit = [
    "tests/*",
    "*/migrations/*"
]

[tool.coverage.report]
skip_empty = true

[tool.black]
line-length = 120
#skip-string-normalization = true
target-version = ["py310", "py314"]
force-exclude = """
/(
  migrations
  |.*test_.*
)/
"""

[tool.pylint.main]
#fail-under = 8.0
ignore-paths = "^learning/migrations/.*$, ^tests/.*$"
load-plugins = ["pylint_django"]
django-settings-module = "learning.settings"

[tool.pylint.format]
max-line-length = 120

[tool.pylint."MESSAGES CONTROL"]
disable = [
    "too-few-public-methods",
    "missing-module-docstring",
    "fixme"
]

[tool.pylint.design]
max-parents = 13

[tool.isort]
profile = "django"

[tool.bandit]
exclude_dirs = [".venv", "tests"]
skips = ["B403"]  # blacklist_imports pickle

[tool.bandit.assert_used]
skips = [".*/tests/.*\\.py$"]

[tool.djlint]
profile="django"
ignore="H021,T003"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
  "D",    # https://docs.astral.sh/ruff/rules/#pydocstyle-d
  "E",    # https://docs.astral.sh/ruff/rules/#error-e
  "F",    # https://docs.astral.sh/ruff/rules/#pyflakes-f
  "I",    # https://docs.astral.sh/ruff/rules/#isort-i
  "N",    # https://docs.astral.sh/ruff/rules/#pep8-naming-n
  "S",    # https://docs.astral.sh/ruff/rules/#flake8-bandit-s
  "W",    # https://docs.astral.sh/ruff/rules/#warning-w
]
ignore = [
  "D100",     # Missing docstring in public module
#  "D101",     # Missing docstring in public class
#  "D400",     # First line should end with a period
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
  "D104",     # Missing docstring in public package
  "E402",     # Module level import not at top of file
]
"main.py" = [
  "E402",     # Module level import not at top of file
]
"tests/*" = [
  "D103",     # Missing docstring in public function
  "S101",     # Use of `assert` detected

]
"migrations/*" = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"  # Accepts one of {google,numpy,pep257}

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

[tool.yamlfix]
allow_duplicate_keys = true
line_length = 120
none_representation = ""
whitelines = 1
section_whitelines = 1
sequence_style = "keep_style"
# the following are default settings
indent_mapping = 2
indent_offset = 2
indent_sequence= 4
comments_min_spaces_from_content = 2
comments_require_starting_space = true
explicit_start = true
quote_keys_and_basic_values = false
quote_representation = "'"
