# Generated by Django 6.0.4 on 2026-05-06 08:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_course_name', message='Enter a valid course name. Must have at least one word. Letters, numbers, underscores, spaces and basic punctuation allowed up to 200 characters.', regex="^(?![^\\w]*$)(?!.*[.,:!?'()&/\\-]{2,})[\\w.,:!?'()&/\\- ]*[A-Za-z0-9][\\w.,:!?'()&/\\- ]*$")], verbose_name='Course name:')),
                ('course_description', models.TextField(max_length=4000, validators=[django.core.validators.RegexValidator(code='invalid_course_description', message='Enter a valid course description. Descriptions may include letters, numbers, spaces and punctuation, and must be between 20 and 4000 characters.', regex='^[\\p{L}\\p{N}\\p{P}\\p{Zs}\\n\\r]{20,4000}$')], verbose_name='Course description:')),
                ('renewal_period', models.IntegerField(choices=[(0, 'no renewal'), (1, '1 year'), (3, '3 years')], db_default=1, default=1, verbose_name='Renewal period:')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='Select if this is a mandatory course.')),
                ('date_added', models.DateField(blank=True, null=True, verbose_name='Course added to training set.')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(error_messages={'invalid': 'Please enter a valid date (DD/MM/YYYY).'}, verbose_name='Course completion date:')),
                ('training_expiry_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='learning.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='unique_course', violation_error_message='You already have this course. Please update it rather than adding new.')],
            },
        ),
    ]
