# Generated by Django 6.0.5 on 2026-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="date_added",
            field=models.DateField(blank=True, null=True, verbose_name="Date added to training set:"),
        ),
    ]
