---
name: Dependency Audit
run-name: ${{ github.workflow }} - ${{ github.actor }}

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pip-audit:
    name: pip-audit
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Install application and audit dependencies
        run: |-
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then pip install .; fi
          pip install pip-audit

      - name: Audit installed Python packages
        run: |
          pip-audit
