---
name: Release
run-name: ${{ github.workflow }} - ${{ github.actor }} pushed a change to ${{ github.ref_name }}

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

  steps:
    name: Release Please
    uses: googleapis/release-please-action@v4
    with:
      release-type: simple
      config-file: release-please-config.json
      manifest-file: .release-please-manifest.json
